apiVersion: v1
kind: Service
metadata:
  labels:
    app: BE
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: {{ .Values.service.protocol }} 
    targetPort: {{ .Values.service.targetPort }} 
  selector:
    app: BE
  type: {{ .Values.service.type }} 